### ISSUE TITLE
Add a bi-directional integration testing suite

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#10]
Add a mechanism in which we can write specify integration tests in the following form:

```
<test name>/
    <schema>.json
    <dry>.json
    <wet>.json
```

The test runner will go through each of this directory and test using the schema to go from dry to wet, and from wet to dry, and report back the results.

**Comment by emberian** [comment]
There's some of this in https://github.com/resin-io/reconfix/blob/rust/tests/testdata/mapping/bidi_6, although the code using it hasn't been written yet. I stole those from the nodejs test suite. The format is

```
explanation of test result
schema
wet
dry
```

I think.

**Comment by jviotti** [comment]
Oh cool, that's exactly what I was looking for. I'll keep this issue open until a runner gets implemented

**Comment by zrzka** [comment]
Closing as obsolote.
