### ISSUE TITLE
Integrate a Rust code coverage tool

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#11]
This project will deal almost exclusively with pure code, which means that we will get a huge code coverage number even with a decent amount of testing.

Let's integrate a code coverage tool that can highlight how many times each line is executed, as a way to prioritize unit testing efforts

**Comment by emberian** [comment]
I've setup kcov and codecov for this purpose in the past. The current "easy" state of the art is to use something like travis-cargo or cargo-travis and coveralls.io.

**Comment by jviotti** [comment]
Sounds awesome, thanks a lot!
