### ISSUE TITLE
Enforce document comments

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#16]
Can we somehow enforce functions and other code constructs to have document comments (e.g. https://facility9.com/2016/05/writing-documentation-in-rust/)? 

We heavily rely on annotations (using JSDoc) in various code projects (see Etcher for an example), and we found out is does wonders to clarify the requirements of each function, and to make the whole code more readable/accessible.

**Comment by emberian** [comment]
`#![deny(missing_docs)]` at the top of the crate.

**Comment by jviotti** [comment]
Nice, I'm loving Rust :)

**Comment by emberian** [comment]
Oops, I added the attribute, but didn't close the issue.
