### ISSUE TITLE
Support `else` clauses in template mappings

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#19]
Lets say we have a template mapping where we want a certain template to apply if the value is `1`, and another if its any number, but `1`. For example:

```json
{
  "foo": {
    "mapping": [
      {
        "value": "1",
        "template": {
          "my_property": "1"
        }
      },
      {
        "value": "<<OTHERWISE>>",
        "template": {
          "my_property": "0"
        }
      }
    ]
  }
}
```

What should we replace `<<OTHERWISE>>` with?

We can allow `value` to take an asterisk to represent the `else` clause, or maybe even allow one of the template mappings to contain no `value` at all.

For example:

```json
{
  "foo": {
    "mapping": [
      {
        "value": "1",
        "template": {
          "my_property": "1"
        }
      },
      {        
        "template": {
          "my_property": "0"
        }
      }
    ]
  }
}
```

**Comment by jviotti** [comment]
Omitting the `value` is certainly not an option since it doesn't allow us to go backward. In the example above, if `my_property` is `0`, what would the value of `foo` be?

**Comment by zrzka** [comment]
Closing as obsolote.
