### ISSUE TITLE
Should we support more complex conditionals in the `value` section of template mappings?

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#20]
Let's say that we have a number property `foo` with four different templates. 

- The first template applies if `foo` is `0`
- The second template applies if `foo` is `1`
- The third template applies if `foo` is negative
- The third template applies otherwise

How to we model the above problem?

Also, what if a template depends on another property as well? For example, the schema contains `foo` and `bar` properties, and a certain template of `foo` should apply if `foo` is positive **and** if `bar` equals `baz`.

Should we allow a property to depend on another property?

**Comment by emberian** [comment]
That seems like it opens a huge can of worms into constraint solving and such, especially for the backward case.

**Comment by zrzka** [comment]
Closing as obsolote.
