### ISSUE TITLE
Resolve template matching degree ties when one of the templates contains wildcards

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#22]
For example, consider the following template, of degree 3:

```json
"foo": {
    "bar": "baz",
    "baz": "qux"
}
```

And the following template, also of degree 3, but which contains wildcards:

```json
"foo": {
    "bar": "[[string]]",
    "qux": "[[string]]"
}
```

They both match, but one of them contains wildcards. Which one matches "more"?

**Comment by jviotti** [comment]
I think we should give preference to non-wildcard matches. Maybe wildcard properties can add 0.5 to the degree instead of 1?

**Comment by zrzka** [comment]
Closing as obsolote.
