### ISSUE TITLE
Allow inserting entropy to images

### ISSUE THREAD

**Issue by jviotti** [resin-io/reconfix#8]
> because images are cloned, they all start with the same entropy, which means you can have an attack where you can somewhat-predict the pseudo-random generator if on boot the device hasn't had enough time to gather entropy

We can do it by populating `/var/lib/systemd/random-seed` (at least in the case of systemd images): https://www.freedesktop.org/software/systemd/man/systemd-random-seed.service.html

**Comment by alexandrosm** [comment]
I really don't think this is a reconfix feature but an Etcher feature. It's
not about the source of truth.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

On Fri, Feb 10, 2017 at 11:23 AM, Juan Cruz Viotti <notifications@github.com

**Comment by lurch** [comment]
Buildroot also has (or had) something similar
https://www.google.co.uk/search?q=buildroot+random+seed

> I really don't think this is a reconfix feature but an Etcher feature. It's not about the source of truth.

In philosophical terms perhaps it doesn't belong in reconfix, but perhaps it does make sense in practical terms (with reconfix being the one program that writes to files _within_ raw filesystem/disk images).
Or perhaps the best-of-both-worlds is for Etcher to be responsible for generating the random data, so as far as reconfix would be concerned it'd just be raw binary data to be written to a particular file in the filesystem. (is that something that reconfix supports, or does it currently _only_ deal with text files?)
Or perhaps I'm muddling up my metaphors.

**Comment by alexandrosm** [comment]
In my mind, Etcher may gain other functionalities like extending
partitions, inserting bootloaders and whatnot. This is a feature that fits
in with those. Reconfix is about creating a virtual source of truth and
reflecting alterations from and to its constituent sources. Unless we're
thinking about altering this file in re-configuration runs, this doesn't
seem to fit.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment]
> In philosophical terms perhaps it doesn't belong in reconfix, but perhaps it does make sense in practical terms (with reconfix being the one program that writes to files within raw filesystem/disk images).

This was my first instinct, but I agree with @alexandrosm that Reconfix might not be the best place for this. I'll move it to the Etcher repository.

**Comment by jviotti** [comment]
See https://github.com/resin-io/etcher/issues/1099
